-- ============================================================
-- AI Product Manager Copilot — Initial Schema Migration
-- Version: 1.0.0  |  Modules: 1, 2, 3
-- Database: PostgreSQL 15+
-- Run: psql -U postgres -d ai_pm_copilot -f init_schema.sql
-- ============================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================
-- TABLE: users
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    user_id         UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    email           VARCHAR(255)    NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    full_name       VARCHAR(255),
    role            VARCHAR(50)     NOT NULL CHECK (role IN ('product_manager', 'customer')),
    project_id      UUID,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    last_login_at   TIMESTAMPTZ,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_users_email        ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_role         ON users (role);
CREATE INDEX IF NOT EXISTS idx_users_project_id   ON users (project_id);

COMMENT ON TABLE  users               IS 'Stores product_manager and customer accounts with RBAC.';
COMMENT ON COLUMN users.user_id       IS 'UUID primary key, auto-generated by gen_random_uuid()';
COMMENT ON COLUMN users.email         IS 'Unique login email address';
COMMENT ON COLUMN users.password_hash IS 'bcrypt hashed password';
COMMENT ON COLUMN users.role          IS 'product_manager or customer';
COMMENT ON COLUMN users.is_active     IS 'Soft delete flag; FALSE = account disabled';

-- ============================================================
-- TABLE: raw_feedback
-- ============================================================
CREATE TABLE IF NOT EXISTS raw_feedback (
    feedback_id             UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    source                  VARCHAR(50)     NOT NULL CHECK (source IN ('csv_upload', 'text_form')),
    submitted_by_role       VARCHAR(50)     NOT NULL CHECK (submitted_by_role IN ('product_manager', 'customer')),
    user_id                 UUID            NOT NULL REFERENCES users(user_id) ON DELETE SET NULL,
    project_id              UUID            NOT NULL,
    customer_name           VARCHAR(255),
    customer_email          VARCHAR(255),
    subject                 TEXT            NOT NULL CONSTRAINT chk_raw_subject_not_empty CHECK (LENGTH(TRIM(subject)) > 0),
    description             TEXT            NOT NULL CONSTRAINT chk_raw_description_not_empty CHECK (LENGTH(TRIM(description)) > 0),
    priority                VARCHAR(50)     NOT NULL DEFAULT 'Medium' CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')),
    category                VARCHAR(100)    NOT NULL DEFAULT 'General' CHECK (category IN ('Bug', 'Feature Request', 'Improvement', 'Complaint', 'General')),
    product_name            VARCHAR(255),
    product_version         VARCHAR(100),
    submission_date         DATE,
    tags                    TEXT[],
    sentiment_self_reported VARCHAR(50) CHECK (sentiment_self_reported IN ('Positive', 'Negative', 'Neutral') OR sentiment_self_reported IS NULL),
    language                VARCHAR(10)     NOT NULL DEFAULT 'en',
    upload_timestamp        TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    raw_metadata            JSONB           NOT NULL DEFAULT '{}',
    canonical_json          JSONB           NOT NULL DEFAULT '{}',
    weight                  INTEGER         NOT NULL DEFAULT 1 CHECK (weight >= 1),
    duplicate_group_id      UUID,
    processing_status       VARCHAR(50)     NOT NULL DEFAULT 'pending' CHECK (processing_status IN ('pending', 'processing', 'processed', 'duplicate', 'failed')),
    processing_error        TEXT,
    processed_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_raw_feedback_processing_status   ON raw_feedback (processing_status);
CREATE INDEX IF NOT EXISTS idx_raw_feedback_project_id          ON raw_feedback (project_id);
CREATE INDEX IF NOT EXISTS idx_raw_feedback_user_id             ON raw_feedback (user_id);
CREATE INDEX IF NOT EXISTS idx_raw_feedback_upload_timestamp    ON raw_feedback (upload_timestamp ASC);
CREATE INDEX IF NOT EXISTS idx_raw_feedback_duplicate_group_id  ON raw_feedback (duplicate_group_id) WHERE duplicate_group_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_raw_feedback_source              ON raw_feedback (source);
CREATE INDEX IF NOT EXISTS idx_raw_feedback_category_priority   ON raw_feedback (category, priority);
CREATE INDEX IF NOT EXISTS idx_raw_feedback_project_status      ON raw_feedback (project_id, processing_status);
CREATE INDEX IF NOT EXISTS idx_raw_feedback_batch_id            ON raw_feedback USING GIN ((raw_metadata -> 'batch_id'));
CREATE INDEX IF NOT EXISTS idx_raw_feedback_subject_fts         ON raw_feedback USING GIN (to_tsvector('english', subject));
CREATE INDEX IF NOT EXISTS idx_raw_feedback_description_fts     ON raw_feedback USING GIN (to_tsvector('english', description));

COMMENT ON TABLE  raw_feedback                   IS 'Raw ingested feedback. Source of truth. Awaits Module 3 processing.';
COMMENT ON COLUMN raw_feedback.weight            IS 'Semantic frequency: 1 + number of duplicates merged into this record';
COMMENT ON COLUMN raw_feedback.duplicate_group_id IS 'Shared UUID for all semantically similar records. NULL until Module 3 runs.';
COMMENT ON COLUMN raw_feedback.processing_status  IS 'Lifecycle: pending→processing→processed|duplicate|failed';

-- ============================================================
-- TABLE: processed_feedback
-- ============================================================
CREATE TABLE IF NOT EXISTS processed_feedback (
    processed_id                UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    raw_feedback_id             UUID            NOT NULL REFERENCES raw_feedback(feedback_id) ON DELETE CASCADE,
    source                      VARCHAR(50)     NOT NULL CHECK (source IN ('csv_upload', 'text_form')),
    submitted_by_role           VARCHAR(50)     NOT NULL CHECK (submitted_by_role IN ('product_manager', 'customer')),
    user_id                     UUID            NOT NULL,
    project_id                  UUID            NOT NULL,
    original_subject            TEXT            NOT NULL,
    original_description        TEXT            NOT NULL,
    clean_text                  TEXT            NOT NULL,
    standardized_text           TEXT            NOT NULL,
    tokens                      TEXT[]          NOT NULL DEFAULT '{}',
    lemmas                      TEXT[]          NOT NULL DEFAULT '{}',
    priority                    VARCHAR(50)     NOT NULL DEFAULT 'Medium' CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')),
    category                    VARCHAR(100)    NOT NULL DEFAULT 'General' CHECK (category IN ('Bug', 'Feature Request', 'Improvement', 'Complaint', 'General')),
    product_name                VARCHAR(255),
    product_version             VARCHAR(100),
    tags                        TEXT[],
    sentiment_self_reported     VARCHAR(50) CHECK (sentiment_self_reported IN ('Positive', 'Negative', 'Neutral') OR sentiment_self_reported IS NULL),
    language                    VARCHAR(10)     NOT NULL DEFAULT 'en',
    submission_date             DATE,
    weight                      INTEGER         NOT NULL DEFAULT 1 CHECK (weight >= 1),
    duplicate_group_id          UUID            NOT NULL,
    word_count                  INTEGER         NOT NULL DEFAULT 0 CHECK (word_count >= 0),
    char_count                  INTEGER         NOT NULL DEFAULT 0 CHECK (char_count >= 0),
    token_count                 INTEGER         NOT NULL DEFAULT 0 CHECK (token_count >= 0),
    lemma_count                 INTEGER         NOT NULL DEFAULT 0 CHECK (lemma_count >= 0),
    processing_metadata         JSONB           NOT NULL DEFAULT '{}',
    processing_status           VARCHAR(50)     NOT NULL DEFAULT 'processed' CHECK (processing_status IN ('processed', 'failed', 'reprocessing')),
    processing_error            TEXT,
    search_vector               TSVECTOR,
    processing_timestamp        TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    ready_for_classification    BOOLEAN         NOT NULL DEFAULT TRUE,
    classified_at               TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_processed_feedback_ready         ON processed_feedback (ready_for_classification, classified_at) WHERE ready_for_classification = TRUE AND classified_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_processed_feedback_project_id    ON processed_feedback (project_id);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_dup_group     ON processed_feedback (duplicate_group_id);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_weight        ON processed_feedback (weight DESC);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_category      ON processed_feedback (category);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_priority      ON processed_feedback (priority);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_raw_id        ON processed_feedback (raw_feedback_id);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_fts           ON processed_feedback USING GIN (search_vector);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_status        ON processed_feedback (processing_status);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_ts            ON processed_feedback (processing_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_project_weight ON processed_feedback (project_id, weight DESC);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_tokens_gin    ON processed_feedback USING GIN (tokens);
CREATE INDEX IF NOT EXISTS idx_processed_feedback_lemmas_gin    ON processed_feedback USING GIN (lemmas);

COMMENT ON TABLE  processed_feedback                         IS 'NLP-processed canonical feedback. One row per semantic cluster. Ready for Module 4.';
COMMENT ON COLUMN processed_feedback.tokens                  IS 'NLTK token list with stop words removed (TEXT array)';
COMMENT ON COLUMN processed_feedback.lemmas                  IS 'spaCy lemmatized token list (TEXT array)';
COMMENT ON COLUMN processed_feedback.search_vector           IS 'Weighted tsvector: A=subject, B=clean_text (auto via trigger)';
COMMENT ON COLUMN processed_feedback.ready_for_classification IS 'TRUE when NLP complete; Module 4 reads WHERE this=TRUE AND classified_at IS NULL';

-- ============================================================
-- TRIGGER FUNCTIONS
-- ============================================================

-- Auto-update search_vector (weights: subject=A, clean_text=B)
CREATE OR REPLACE FUNCTION update_processed_feedback_search_vector()
RETURNS TRIGGER AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', COALESCE(NEW.original_subject, '')), 'A')
        ||
        setweight(to_tsvector('english', COALESCE(NEW.clean_text, '')), 'B');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_processed_feedback_search_vector ON processed_feedback;
CREATE TRIGGER trg_processed_feedback_search_vector
    BEFORE INSERT OR UPDATE OF original_subject, clean_text
    ON processed_feedback
    FOR EACH ROW
    EXECUTE FUNCTION update_processed_feedback_search_vector();

-- Auto-update updated_at on any UPDATE (shared by all tables)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS trg_raw_feedback_updated_at ON raw_feedback;
CREATE TRIGGER trg_raw_feedback_updated_at
    BEFORE UPDATE ON raw_feedback FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS trg_processed_feedback_updated_at ON processed_feedback;
CREATE TRIGGER trg_processed_feedback_updated_at
    BEFORE UPDATE ON processed_feedback FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- END OF MIGRATION
-- ============================================================
