import React, { useState, useContext, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { AuthContext } from '../context/AuthContext';
import api from '../services/api';

const RegisterPage = () => {
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    full_name: '',
    role: 'customer',
    project_id: ''
  });

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);

  const { isAuthenticated, user } = useContext(AuthContext);
  const navigate = useNavigate();

  // If already logged in, redirect based on role
  useEffect(() => {
    if (isAuthenticated && user) {
      navigate(user.role === 'product_manager' ? '/dashboard' : '/upload/feedback');
    }
  }, [isAuthenticated, user, navigate]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!formData.email || !formData.password || !formData.role) {
      setError("Please fill out all required fields.");
      return;
    }

    setLoading(true);
    setError(null);
    setSuccess(false);

    try {
      const response = await api.post('/auth/register', formData);
      if (response.data.success) {
        setSuccess(true);
        setTimeout(() => {
          navigate('/login');
        }, 2000);
      } else {
        setError(response.data.error || "Registration failed.");
      }
    } catch (err) {
      console.error(err);
      setError(err.response?.data?.error || "Network error. Failed to register.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-page-container">
      <div className="auth-card glass-panel">
        <div className="auth-header">
          <h2>Create Account</h2>
          <p>Get started with AI Product Manager Copilot</p>
        </div>

        <form onSubmit={handleSubmit} className="standard-form">
          <div className="form-group">
            <label htmlFor="full_name">Full Name</label>
            <input
              type="text"
              id="full_name"
              name="full_name"
              value={formData.full_name}
              onChange={handleInputChange}
              placeholder="Jane Doe"
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">Email Address *</label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleInputChange}
              placeholder="name@company.com"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Password *</label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleInputChange}
              placeholder="••••••••"
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="role">Role *</label>
            <select
              id="role"
              name="role"
              value={formData.role}
              onChange={handleInputChange}
              required
            >
              <option value="customer">Customer</option>
              <option value="product_manager">Product Manager</option>
            </select>
          </div>

          {formData.role === 'product_manager' && (
            <div className="form-group">
              <label htmlFor="project_id">Project ID / Workspace ID (Optional UUID)</label>
              <input
                type="text"
                id="project_id"
                name="project_id"
                value={formData.project_id}
                onChange={handleInputChange}
                placeholder="UUID string (autogenerated if blank)"
              />
            </div>
          )}

          <button type="submit" className="action-btn auth-submit-btn" disabled={loading}>
            {loading ? "Registering..." : "Register"}
          </button>
        </form>

        {error && (
          <div className="alert-message error-alert auth-alert">
            {error}
          </div>
        )}

        {success && (
          <div className="alert-message success-alert auth-alert">
            Registration successful! Redirecting to login...
          </div>
        )}

        <div className="auth-footer">
          <p>Already have an account? <Link to="/login" className="auth-link">Sign in here</Link></p>
        </div>
      </div>
    </div>
  );
};

export default RegisterPage;
